#! /bin/sh

# Launch Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap br &
dbus-launch pcmanfm --daemon &
xsetroot -cursor_name left_ptr &

# Feh randomize Wallpapers after period time
while true; do feh --randomize --bg-fill ~/Pictures/Wallpapers; sleep 600; done &

# Launch polybar
$HOME/.config/polybar/launch.sh &

# Launch picom--ibhagwan-git
picom --experimental-backends --config ~/.config/picom/picom.conf &

#Launch Dunst
/usr/bin/dunst &
#pulseaudio &

# Audio if using pipewire

#pipewire &
#pipewire-pulse &
#pipewire-media-session &

# Bluetooth (wireplumber or pipewire-media-session)

#bluetoothctl power on &
#wireplumber &

# Polkit authentication
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# For mounting 
udevil &
devmon &

# Fix error java apps on bspwm
wmname LG3D &
#$HOME/.config/polybar/scripts/polybar_autohide/autohide &

# Add font path
#xset +fp /home/junior/.local/share/fonts/ &
#xset fp rehash &

#XDG DATA DIR
export XDG_DATA_DIRS="$HOME/.local/share/applications" &

# XDG USER DIR
#mkdir -p /tmp/${USER}-runtime && chmod -R 0700 /tmp/${USER}-runtime &
#export XDG_RUNTIME_DIR=/tmp/${USER}-runtime &

if [ -z "${XDG_RUNTIME_DIR}" ]; then
        export XDG_RUNTIME_DIR="/tmp/runtime-dir-${UID}"
        if [ ! -d "${XDG_RUNTIME_DIR}" ]; then
                mkdir "${XDG_RUNTIME_DIR}"
                chmod 0700 "${XDG_RUNTIME_DIR}"
        fi
fi &


# Flatpak
export XDG_RUNTIME_DIR="/var/lib/flatpak/exports/share" &
export XDG_RUNTIME_DIR="/home/juca/.local/share/flatpak/exports/share" &

# Bspwm check if has another monitor
~/.local/bin/dualbsp.sh &

~/.conky/conky-startup.sh &

# -------------------------#
# BSPWM THEMES - - - - - - #
# -------------------------#

# Dracula
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
#bspc config presel_feedback_color "#6272a4"

# Catpuccin
bspc config normal_border_color "#1E1E2E"
bspc config active_border_color " #1E1E2E"
bspc config focused_border_color "#96CDFB"
bspc config presel_feedback_color "#96CDFB"

#-------------------------#
# BSPWM CONFIGURATION - - #
#-------------------------#

bspc config border_radius				 					0
bspc config border_width         					2
bspc config window_gap           					6

bspc config top_padding               		18
bspc config bottom_padding            		0
bspc config left_padding              		0
bspc config right_padding             		0

#bspc config automatic_scheme 	 					spiral

bspc config click_to_focus       					true
bspc config split_ratio          					0.50
bspc config borderless_monocle   					true
bspc config gapless_monocle      					true
bspc config single_monocle       					false
bspc config paddingless_monocle  					true
bspc config focus_by_distance         		true
bspc config focus_follows_pointer     		true
bspc config history_aware_focus       		true
bspc config remove_disabled_monitors			true
bspc config merge_overlapping_monitors    true
bspc config ignore_ewmh_focus 		  			true

bspc config pointer_modifier 							mod4
bspc config pointer_action1 							move
bspc config pointer_action2 							resize_side
bspc config pointer_action3 							resize_corner

## BSPWM RULES ========================== # 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Virt-manager desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating desktop='^8'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='^2' state=tiled follow=true
# bspc rule -a kitty desktop='^4' follow=true
bspc rule -a Code desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Brave-browser desktop='^3' state=tiled follow=true
bspc rule -a Pcmanfm state=floating follow=on desktop='^6'
bspc rule -a Rhythmbox state=tiled desktop='^4' follow=on
bspc rule -a VSCodium state=tiled desktop='^1' follow=on
bspc rule -a virt-manager state=tiled desktop='^7' follow=on
bspc rule -a Pavucontrol state=tiled desktop='^4' follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Gpick state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Timeshift-gtk state=floating follow=on
bspc rule -a Xfce4-power-manager-settings state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Engrampa state=floating follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Anki desktop=^1 state=monocole follow=false
bspc rule -a stacer state=floating
bspc rule -a Lightdm-gtk-greeter-settings state=floating
