#! /bin/sh

$HOME/.config/bspwm/autostart.sh

# -------------------------#
# BSPWM THEMES - - - - - - #
# -------------------------#

#Single monitor
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Dracula
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
#bspc config presel_feedback_color "#6272a4"

# Catpuccin
bspc config normal_border_color 					"#1E1E2E"
bspc config active_border_color 					"#1E1E2E"
bspc config focused_border_color 					"#96CDFB"
bspc config presel_feedback_color 					"#96CDFB"

#-------------------------#
# BSPWM CONFIGURATION - - #
#-------------------------#

bspc config border_radius 							0
bspc config border_width 							2
bspc config window_gap 								6

bspc config top_padding 							18
bspc config bottom_padding 							0
bspc config left_padding 							0
bspc config right_padding 							0

#bspc config automatic_scheme 	 					spiral

bspc config click_to_focus 							true
bspc config split_ratio 							0.50
bspc config borderless_monocle 						true
bspc config gapless_monocle 						true
bspc config single_monocle 							false
bspc config paddingless_monocle 					true
bspc config focus_by_distance 						true
bspc config focus_follows_pointer 					true
bspc config history_aware_focus 					true
bspc config remove_disabled_monitors 				true
bspc config merge_overlapping_monitors 				true
bspc config ignore_ewmh_focus 						true
bspc config remove_disabled_monitors 				true


bspc config pointer_modifier 						mod4
bspc config pointer_action1 						move
bspc config pointer_action2 						resize_side
bspc config pointer_action3 						resize_corner

## BSPWM RULES ========================== #

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Virt-manager desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating desktop='^8'
bspc rule -a qalculate-gtk state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='^2' state=tiled follow=true
# bspc rule -a kitty desktop='^4' follow=true
bspc rule -a Code desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Brave-browser desktop='^3' state=tiled follow=true
bspc rule -a Pcmanfm state=floating follow=on desktop='^6'
bspc rule -a Rhythmbox state=tiled desktop='^4' follow=on
bspc rule -a VSCodium state=tiled desktop='^1' follow=on
bspc rule -a virt-manager state=tiled desktop='^7' follow=on
bspc rule -a Pavucontrol state=tiled desktop='^4' follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Gpick state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Timeshift-gtk state=floating follow=on
bspc rule -a Xfce4-power-manager-settings state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Engrampa state=floating follow=on
bspc rule -a stacer state=floating
bspc rule -a Lightdm-gtk-greeter-settings state=floating
bspc rule -a '*:zathura' state=tiled


#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window