#! /bin/sh

#bspc monitor HDMI-1-0 -d I II III IV
#bspc monitor (eDP1/LVDS-1) -d V VI VII VIII IX X

#####           MONITORES       ######

# Dracula
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Floating Windows
declare -a floats=(Alafloat Lxappearence Arandr
    Pcmanfm feh Nm-connection-editor Yad Gpick)
for i in ${floats[@]}; do
    bspc rule - $i state=floating follow=on focus=on
done

# Kill if already running
killal -9 picom sxhkd dunst polybar

#Launch Polybar
/home/${USER}/.config/polybar/launch.sh &

#Launch Xresouces
xrdb /home/${USER}/.Xresources &

#Launch compositor
picom -f &

# Feh
$HOME/.local/bin/fehauto.sh &

# sxhkd &
pgrep -x sxhkd >/dev/null || sxhkd &

# Fix pointer
xsetroot -cursor_name left_ptr

# Dual Monitor
/home/${USER}/.bin/dualbsp.sh &

#bspc monitor -d I II III IV V VI VII VIII IX X
#~/.bin/dualbsp-VM.sh
setxkbmap br &
#pcmanfm --desktop &
#xsetroot -cursor_name left_ptr &
lxqt-policykit-agent &
udevil &
devmon &
#$HOME/.bin/dualbsp-VM.sh

#mkdir -p /tmp/${USER}-runtime && chmod -R 0700 /tmp/${USER}-runtime &
#export XDG_RUNTIME_DIR=/tmp/${USER}-runtime &

# Add font path
#xset +fp /home/junior/.local/share/fonts/ &
#xset fp rehash &

#XDG DATA DIR
export XDG_DATA_DIRS="$HOME/.local/share/applications"

# XDG USER DIR
mkdir -p /tmp/${USER}-runtime && chmod -R 0700 /tmp/${USER}-runtime &
export XDG_RUNTIME_DIR=/tmp/${USER}-runtime &
export XDG_RUNTIME_DIR="/var/lib/flatpak/exports/share" &
export XDG_RUNTIME_DIR="/home/juca/.local/share/flatpak/exports/share" &

~/.bin/dualbsp.sh
