#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-1-0 -d I II III IV 
#bspc monitor eDP1 -d V VI VII VIII IX X

#####           MONITORES       ######


/home/junior/.config/bspwm/dualbsp.sh
xrdb ${HOME}/.Xresources &
$HOME/.config/polybar/launch.sh &
export $(dbus-launch) &
$HOME/.fehbg

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off