#! /bin/sh

#bspc monitor HDMI-1-0 -d I II III IV 
#bspc monitor (eDP1/LVDS-1) -d V VI VII VIII IX X

#####           MONITORES       ######

# Dracula
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Floating Windows
declare -a floats=(Alafloat Lxappearence Arandr \
Pcmanfm feh Nm-connection-editor Yad Gpick)
for i in ${floats[@]}; do
    bspc rule - $i state=floating follow=on focus=on; done

# Kill if already running
killal -9 picom sxhkd dunst polybar

#Launch Polybar
/home/${USER}/.config/polybar/launch.sh &

#Launch Xresouces 
xrdb /home/${USER}/.Xresources &

#Launch compositor
picom -f &

# Feh
feh --bg-fill /home/${USER}/Pictures/wallpapers/wallpaper.jpg &

# sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &

# Fix pointer
xsetroot -cursor_name left_ptr

# Dual Monitor
/home/${USER}/.config/bspwm/dualbsp.sh &
