#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

setxkbmap br &
light-locker &
/usr/bin/dunst &
bash /home/junior/.config/polybar/forest/launch.sh &
nitrogen --restore
xrandr --output eDP1 --mode 1920x1080 &
# picom --no-fading-openclose &

bspc monitor eDP1 -d I II III IV
bspc monitor HDMI-1-0 -d V VI VII VIII
bspc config border_width 0
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^5'
bspc rule -a Virt-manager desktop='^4' state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
